### PR TITLE
bugfix: fix get error cmd status code

### PR DESCRIPTION
**Pull request by hongliang5316**
bugfix: fix get error cmd exit status code
feat: support tcp reuseaddr & fix coding style

Signed-off-by: hongliang <513918845@qq.com>

### CODE REVIEW

**Comment by juce** [comment]
couple things:
1. i pushed the whitespace clean-up, so no need for that in your pull request anymore. Please re-submit. The tcp reuseaddr is a good idea.
2. why do you want WEXITSTATUS? I don't think sockproc needs to make any assumptions or processing of status code returned by the subprocess.

**Comment by hongliang5316** [comment]
@juce 
i think `WEXITSTATUS(child_exit_code)` is an exactly child process exit code, for example, on my centos7 if my `cmd` exit with code `3`,  but `sockproc` return status is `768`, while using WEXITSTATUS(child_exit_code) is exactly
this is the `WEXITSTATUS` description:
`returns the exit status of the child.  This consists of the least significant 8 bits of the status argument that the child specified in a call to exit(3) or _exit(2) or as the argument for a return statement in main().  This macro should be employed only if WIFEXITED returned true.`

**Comment by juce** [comment]
sounds good, thanks

**Comment by juce** [comment]
@hongliang5316 

actually, i thought more about it and reverted the WEXITSTATUS change.

Here's my thinking: I don't really want to analyze child process exit status value in sockproc - the caller can do that, if they need/want to - and they have more flexibility: they can call WIFEXITED, WIFSIGNALED, and other macros (as documented here: https://www.mirbsd.org/htman/i386/man2/wait.htm ) - depending on what the situation is. The sockproc client may or may not care if the child process exited properly, or was signaled to stop or core-dumped, etc. All of that can be determined from the status code returned by sockproc.

I kept your socket-reuse change though. That was good :)

Thanks!

**Comment by hongliang5316** [comment]
@juce 
Hello, i agree with you.
I think you can let https://github.com/juce/lua-resty-shell support get `WEXITSTATUS(exit_status)` :)

**Pull request merged**
